//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:12:40 PM BRST 
//


package org.iso.mpeg.mpegv._2010.dcdv;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.iso.mpeg.mpegv._2010.cidl.SensoryDeviceCapabilityBaseType;


/**
 * <p>Java class for HeatingCapabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeatingCapabilityType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg-v:2010:01-CIDL-NS}SensoryDeviceCapabilityBaseType">
 *       &lt;attribute name="maxIntensity" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="minIntensity" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="unit" type="{urn:mpeg:mpeg-v:2010:01-CT-NS}unitType" />
 *       &lt;attribute name="numOfLevels" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeatingCapabilityType")
public class HeatingCapabilityType
    extends SensoryDeviceCapabilityBaseType
{

    @XmlAttribute(name = "maxIntensity")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxIntensity;
    @XmlAttribute(name = "minIntensity")
    protected BigInteger minIntensity;
    @XmlAttribute(name = "unit")
    protected String unit;
    @XmlAttribute(name = "numOfLevels")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numOfLevels;

    /**
     * Gets the value of the maxIntensity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxIntensity() {
        return maxIntensity;
    }

    /**
     * Sets the value of the maxIntensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxIntensity(BigInteger value) {
        this.maxIntensity = value;
    }

    /**
     * Gets the value of the minIntensity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinIntensity() {
        return minIntensity;
    }

    /**
     * Sets the value of the minIntensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinIntensity(BigInteger value) {
        this.minIntensity = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the numOfLevels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumOfLevels() {
        return numOfLevels;
    }

    /**
     * Sets the value of the numOfLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumOfLevels(BigInteger value) {
        this.numOfLevels = value;
    }

}
