//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:12:40 PM BRST 
//


package org.iso.mpeg.mpegv._2010.dcdv;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.iso.mpeg.mpegv._2010.cidl.SensoryDeviceCapabilityBaseType;


/**
 * <p>Java class for TactileCapabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TactileCapabilityType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg-v:2010:01-CIDL-NS}SensoryDeviceCapabilityBaseType">
 *       &lt;attribute name="intensityUnit" type="{urn:mpeg:mpeg-v:2010:01-CT-NS}unitType" />
 *       &lt;attribute name="maxValue" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="minValue" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="arraysizeX" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="arraysizeY" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="gapX" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="gapY" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="gapUnit" type="{urn:mpeg:mpeg-v:2010:01-CT-NS}unitType" />
 *       &lt;attribute name="maxUpdateRate" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="updateRateUnit" type="{urn:mpeg:mpeg-v:2010:01-CT-NS}unitType" />
 *       &lt;attribute name="actuatorType" type="{urn:mpeg:mpeg7:schema:2004}termReferenceType" />
 *       &lt;attribute name="numOfLevels" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TactileCapabilityType")
public class TactileCapabilityType
    extends SensoryDeviceCapabilityBaseType
{

    @XmlAttribute(name = "intensityUnit")
    protected String intensityUnit;
    @XmlAttribute(name = "maxValue")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxValue;
    @XmlAttribute(name = "minValue")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger minValue;
    @XmlAttribute(name = "arraysizeX")
    protected BigInteger arraysizeX;
    @XmlAttribute(name = "arraysizeY")
    protected BigInteger arraysizeY;
    @XmlAttribute(name = "gapX")
    protected Float gapX;
    @XmlAttribute(name = "gapY")
    protected Float gapY;
    @XmlAttribute(name = "gapUnit")
    protected String gapUnit;
    @XmlAttribute(name = "maxUpdateRate")
    protected BigInteger maxUpdateRate;
    @XmlAttribute(name = "updateRateUnit")
    protected String updateRateUnit;
    @XmlAttribute(name = "actuatorType")
    protected String actuatorType;
    @XmlAttribute(name = "numOfLevels")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numOfLevels;

    /**
     * Gets the value of the intensityUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntensityUnit() {
        return intensityUnit;
    }

    /**
     * Sets the value of the intensityUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntensityUnit(String value) {
        this.intensityUnit = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxValue(BigInteger value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinValue(BigInteger value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the arraysizeX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArraysizeX() {
        return arraysizeX;
    }

    /**
     * Sets the value of the arraysizeX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArraysizeX(BigInteger value) {
        this.arraysizeX = value;
    }

    /**
     * Gets the value of the arraysizeY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArraysizeY() {
        return arraysizeY;
    }

    /**
     * Sets the value of the arraysizeY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArraysizeY(BigInteger value) {
        this.arraysizeY = value;
    }

    /**
     * Gets the value of the gapX property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGapX() {
        return gapX;
    }

    /**
     * Sets the value of the gapX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGapX(Float value) {
        this.gapX = value;
    }

    /**
     * Gets the value of the gapY property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getGapY() {
        return gapY;
    }

    /**
     * Sets the value of the gapY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setGapY(Float value) {
        this.gapY = value;
    }

    /**
     * Gets the value of the gapUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGapUnit() {
        return gapUnit;
    }

    /**
     * Sets the value of the gapUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGapUnit(String value) {
        this.gapUnit = value;
    }

    /**
     * Gets the value of the maxUpdateRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxUpdateRate() {
        return maxUpdateRate;
    }

    /**
     * Sets the value of the maxUpdateRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxUpdateRate(BigInteger value) {
        this.maxUpdateRate = value;
    }

    /**
     * Gets the value of the updateRateUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateRateUnit() {
        return updateRateUnit;
    }

    /**
     * Sets the value of the updateRateUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateRateUnit(String value) {
        this.updateRateUnit = value;
    }

    /**
     * Gets the value of the actuatorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActuatorType() {
        return actuatorType;
    }

    /**
     * Sets the value of the actuatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActuatorType(String value) {
        this.actuatorType = value;
    }

    /**
     * Gets the value of the numOfLevels property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumOfLevels() {
        return numOfLevels;
    }

    /**
     * Sets the value of the numOfLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumOfLevels(BigInteger value) {
        this.numOfLevels = value;
    }

}
