//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:39:36 PM BRST 
//


package org.iso.mpeg.mpeg7._2004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiscreteUniformDistributionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscreteUniformDistributionType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}DiscreteDistributionType">
 *       &lt;sequence>
 *         &lt;element name="Range" type="{urn:mpeg:mpeg7:schema:2004}DoubleMatrixType"/>
 *         &lt;element name="Scale" type="{urn:mpeg:mpeg7:schema:2004}DoubleMatrixType" minOccurs="0"/>
 *         &lt;element name="Shift" type="{urn:mpeg:mpeg7:schema:2004}DoubleMatrixType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscreteUniformDistributionType", propOrder = {
    "range",
    "scale",
    "shift"
})
public class DiscreteUniformDistributionType
    extends DiscreteDistributionType
{

    @XmlElement(name = "Range", required = true)
    protected DoubleMatrixType range;
    @XmlElement(name = "Scale")
    protected DoubleMatrixType scale;
    @XmlElement(name = "Shift")
    protected DoubleMatrixType shift;

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleMatrixType }
     *     
     */
    public DoubleMatrixType getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleMatrixType }
     *     
     */
    public void setRange(DoubleMatrixType value) {
        this.range = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleMatrixType }
     *     
     */
    public DoubleMatrixType getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleMatrixType }
     *     
     */
    public void setScale(DoubleMatrixType value) {
        this.scale = value;
    }

    /**
     * Gets the value of the shift property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleMatrixType }
     *     
     */
    public DoubleMatrixType getShift() {
        return shift;
    }

    /**
     * Sets the value of the shift property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleMatrixType }
     *     
     */
    public void setShift(DoubleMatrixType value) {
        this.shift = value;
    }

}
