//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:39:36 PM BRST 
//


package org.iso.mpeg.mpeg7._2004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HyperGeometricDistributionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HyperGeometricDistributionType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}DiscreteDistributionType">
 *       &lt;sequence>
 *         &lt;element name="NumOfSuccesses" type="{urn:mpeg:mpeg7:schema:2004}IntegerMatrixType"/>
 *         &lt;element name="NumOfTrials" type="{urn:mpeg:mpeg7:schema:2004}IntegerMatrixType"/>
 *         &lt;element name="PopulationSize" type="{urn:mpeg:mpeg7:schema:2004}IntegerMatrixType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HyperGeometricDistributionType", propOrder = {
    "numOfSuccesses",
    "numOfTrials",
    "populationSize"
})
public class HyperGeometricDistributionType
    extends DiscreteDistributionType
{

    @XmlElement(name = "NumOfSuccesses", required = true)
    protected IntegerMatrixType numOfSuccesses;
    @XmlElement(name = "NumOfTrials", required = true)
    protected IntegerMatrixType numOfTrials;
    @XmlElement(name = "PopulationSize", required = true)
    protected IntegerMatrixType populationSize;

    /**
     * Gets the value of the numOfSuccesses property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerMatrixType }
     *     
     */
    public IntegerMatrixType getNumOfSuccesses() {
        return numOfSuccesses;
    }

    /**
     * Sets the value of the numOfSuccesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerMatrixType }
     *     
     */
    public void setNumOfSuccesses(IntegerMatrixType value) {
        this.numOfSuccesses = value;
    }

    /**
     * Gets the value of the numOfTrials property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerMatrixType }
     *     
     */
    public IntegerMatrixType getNumOfTrials() {
        return numOfTrials;
    }

    /**
     * Sets the value of the numOfTrials property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerMatrixType }
     *     
     */
    public void setNumOfTrials(IntegerMatrixType value) {
        this.numOfTrials = value;
    }

    /**
     * Gets the value of the populationSize property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerMatrixType }
     *     
     */
    public IntegerMatrixType getPopulationSize() {
        return populationSize;
    }

    /**
     * Sets the value of the populationSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerMatrixType }
     *     
     */
    public void setPopulationSize(IntegerMatrixType value) {
        this.populationSize = value;
    }

}
