//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:39:36 PM BRST 
//


package org.iso.mpeg.mpeg7._2004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LognormalDistributionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LognormalDistributionType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}ContinuousDistributionType">
 *       &lt;sequence>
 *         &lt;element name="NormalMean" type="{urn:mpeg:mpeg7:schema:2004}DoubleMatrixType"/>
 *         &lt;element name="NormalVariance" type="{urn:mpeg:mpeg7:schema:2004}DoubleMatrixType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LognormalDistributionType", propOrder = {
    "normalMean",
    "normalVariance"
})
public class LognormalDistributionType
    extends ContinuousDistributionType
{

    @XmlElement(name = "NormalMean", required = true)
    protected DoubleMatrixType normalMean;
    @XmlElement(name = "NormalVariance", required = true)
    protected DoubleMatrixType normalVariance;

    /**
     * Gets the value of the normalMean property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleMatrixType }
     *     
     */
    public DoubleMatrixType getNormalMean() {
        return normalMean;
    }

    /**
     * Sets the value of the normalMean property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleMatrixType }
     *     
     */
    public void setNormalMean(DoubleMatrixType value) {
        this.normalMean = value;
    }

    /**
     * Gets the value of the normalVariance property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleMatrixType }
     *     
     */
    public DoubleMatrixType getNormalVariance() {
        return normalVariance;
    }

    /**
     * Sets the value of the normalVariance property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleMatrixType }
     *     
     */
    public void setNormalVariance(DoubleMatrixType value) {
        this.normalVariance = value;
    }

}
