//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:38:19 PM BRST 
//


package org.iso.mpeg.mpegv._2010.sev;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mpeg.mpeg_v._2010._01_sev_ns package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mpeg.mpeg_v._2010._01_sev_ns
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShakeType }
     * 
     */
    public ShakeType createShakeType() {
        return new ShakeType();
    }

    /**
     * Create an instance of {@link WindType }
     * 
     */
    public WindType createWindType() {
        return new WindType();
    }

    /**
     * Create an instance of {@link ScentType }
     * 
     */
    public ScentType createScentType() {
        return new ScentType();
    }

    /**
     * Create an instance of {@link PassiveKinestheticMotionType }
     * 
     */
    public PassiveKinestheticMotionType createPassiveKinestheticMotionType() {
        return new PassiveKinestheticMotionType();
    }

    /**
     * Create an instance of {@link RigidBodyMotionType }
     * 
     */
    public RigidBodyMotionType createRigidBodyMotionType() {
        return new RigidBodyMotionType();
    }

    /**
     * Create an instance of {@link CollideType }
     * 
     */
    public CollideType createCollideType() {
        return new CollideType();
    }

    /**
     * Create an instance of {@link FlashType }
     * 
     */
    public FlashType createFlashType() {
        return new FlashType();
    }

    /**
     * Create an instance of {@link TurnType }
     * 
     */
    public TurnType createTurnType() {
        return new TurnType();
    }

    /**
     * Create an instance of {@link TactileType }
     * 
     */
    public TactileType createTactileType() {
        return new TactileType();
    }

    /**
     * Create an instance of {@link InclineType }
     * 
     */
    public InclineType createInclineType() {
        return new InclineType();
    }

    /**
     * Create an instance of {@link LightType }
     * 
     */
    public LightType createLightType() {
        return new LightType();
    }

    /**
     * Create an instance of {@link PassiveKinestheticForceType }
     * 
     */
    public PassiveKinestheticForceType createPassiveKinestheticForceType() {
        return new PassiveKinestheticForceType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link SprayingType }
     * 
     */
    public SprayingType createSprayingType() {
        return new SprayingType();
    }

    /**
     * Create an instance of {@link WaveType }
     * 
     */
    public WaveType createWaveType() {
        return new WaveType();
    }

    /**
     * Create an instance of {@link TactileResourceType }
     * 
     */
    public TactileResourceType createTactileResourceType() {
        return new TactileResourceType();
    }

    /**
     * Create an instance of {@link SpinType }
     * 
     */
    public SpinType createSpinType() {
        return new SpinType();
    }

    /**
     * Create an instance of {@link ColorCorrectionType }
     * 
     */
    public ColorCorrectionType createColorCorrectionType() {
        return new ColorCorrectionType();
    }

    /**
     * Create an instance of {@link VibrationType }
     * 
     */
    public VibrationType createVibrationType() {
        return new VibrationType();
    }

    /**
     * Create an instance of {@link FogType }
     * 
     */
    public FogType createFogType() {
        return new FogType();
    }

    /**
     * Create an instance of {@link MoveTowardType }
     * 
     */
    public MoveTowardType createMoveTowardType() {
        return new MoveTowardType();
    }

    /**
     * Create an instance of {@link ActiveKinestheticForceType }
     * 
     */
    public ActiveKinestheticForceType createActiveKinestheticForceType() {
        return new ActiveKinestheticForceType();
    }

    /**
     * Create an instance of {@link ActiveKinestheticType }
     * 
     */
    public ActiveKinestheticType createActiveKinestheticType() {
        return new ActiveKinestheticType();
    }

}
