//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:38:19 PM BRST 
//


package org.iso.mpeg.mpeg7._2001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaTimeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaTimeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="MediaTimePoint" type="{urn:mpeg:mpeg7:schema:2001}mediaTimePointType"/>
 *           &lt;element name="MediaRelTimePoint" type="{urn:mpeg:mpeg7:schema:2001}MediaRelTimePointType"/>
 *           &lt;element name="MediaRelIncrTimePoint" type="{urn:mpeg:mpeg7:schema:2001}MediaRelIncrTimePointType"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="MediaDuration" type="{urn:mpeg:mpeg7:schema:2001}mediaDurationType"/>
 *           &lt;element name="MediaIncrDuration" type="{urn:mpeg:mpeg7:schema:2001}MediaIncrDurationType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaTimeType", propOrder = {
    "mediaTimePoint",
    "mediaRelTimePoint",
    "mediaRelIncrTimePoint",
    "mediaDuration",
    "mediaIncrDuration"
})
public class MediaTimeType {

    @XmlElement(name = "MediaTimePoint")
    protected String mediaTimePoint;
    @XmlElement(name = "MediaRelTimePoint")
    protected MediaRelTimePointType mediaRelTimePoint;
    @XmlElement(name = "MediaRelIncrTimePoint")
    protected MediaRelIncrTimePointType mediaRelIncrTimePoint;
    @XmlElement(name = "MediaDuration")
    protected String mediaDuration;
    @XmlElement(name = "MediaIncrDuration")
    protected MediaIncrDurationType mediaIncrDuration;

    /**
     * Gets the value of the mediaTimePoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaTimePoint() {
        return mediaTimePoint;
    }

    /**
     * Sets the value of the mediaTimePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaTimePoint(String value) {
        this.mediaTimePoint = value;
    }

    /**
     * Gets the value of the mediaRelTimePoint property.
     * 
     * @return
     *     possible object is
     *     {@link MediaRelTimePointType }
     *     
     */
    public MediaRelTimePointType getMediaRelTimePoint() {
        return mediaRelTimePoint;
    }

    /**
     * Sets the value of the mediaRelTimePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaRelTimePointType }
     *     
     */
    public void setMediaRelTimePoint(MediaRelTimePointType value) {
        this.mediaRelTimePoint = value;
    }

    /**
     * Gets the value of the mediaRelIncrTimePoint property.
     * 
     * @return
     *     possible object is
     *     {@link MediaRelIncrTimePointType }
     *     
     */
    public MediaRelIncrTimePointType getMediaRelIncrTimePoint() {
        return mediaRelIncrTimePoint;
    }

    /**
     * Sets the value of the mediaRelIncrTimePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaRelIncrTimePointType }
     *     
     */
    public void setMediaRelIncrTimePoint(MediaRelIncrTimePointType value) {
        this.mediaRelIncrTimePoint = value;
    }

    /**
     * Gets the value of the mediaDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaDuration() {
        return mediaDuration;
    }

    /**
     * Sets the value of the mediaDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaDuration(String value) {
        this.mediaDuration = value;
    }

    /**
     * Gets the value of the mediaIncrDuration property.
     * 
     * @return
     *     possible object is
     *     {@link MediaIncrDurationType }
     *     
     */
    public MediaIncrDurationType getMediaIncrDuration() {
        return mediaIncrDuration;
    }

    /**
     * Sets the value of the mediaIncrDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaIncrDurationType }
     *     
     */
    public void setMediaIncrDuration(MediaIncrDurationType value) {
        this.mediaIncrDuration = value;
    }

}
