//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:12:40 PM BRST 
//


package org.iso.mpeg.mpegv._2010.scdv;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.iso.mpeg.mpegv._2010.cidl.SensorCapabilityBaseType;


/**
 * <p>Java class for MotionSensorCapabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MotionSensorCapabilityType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg-v:2010:01-CIDL-NS}SensorCapabilityBaseType">
 *       &lt;sequence>
 *         &lt;element name="PositionCapability" type="{urn:mpeg:mpeg-v:2010:01-SCDV-NS}PositionSensorCapabilityType" minOccurs="0"/>
 *         &lt;element name="OrientationCapability" type="{urn:mpeg:mpeg-v:2010:01-SCDV-NS}OrientationSensorCapabilityType" minOccurs="0"/>
 *         &lt;element name="VelocityCapability" type="{urn:mpeg:mpeg-v:2010:01-SCDV-NS}VelocitySensorCapabilityType" minOccurs="0"/>
 *         &lt;element name="AngularVelocityCapability" type="{urn:mpeg:mpeg-v:2010:01-SCDV-NS}AngularVelocitySensorCapabilityType" minOccurs="0"/>
 *         &lt;element name="AccelerationCapability" type="{urn:mpeg:mpeg-v:2010:01-SCDV-NS}AccelerationSensorCapabilityType" minOccurs="0"/>
 *         &lt;element name="AngularAccelerationCapability" type="{urn:mpeg:mpeg-v:2010:01-SCDV-NS}AngularAccelerationSensorCapabilityType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MotionSensorCapabilityType", propOrder = {
    "positionCapability",
    "orientationCapability",
    "velocityCapability",
    "angularVelocityCapability",
    "accelerationCapability",
    "angularAccelerationCapability"
})
public class MotionSensorCapabilityType
    extends SensorCapabilityBaseType
{

    @XmlElement(name = "PositionCapability")
    protected PositionSensorCapabilityType positionCapability;
    @XmlElement(name = "OrientationCapability")
    protected OrientationSensorCapabilityType orientationCapability;
    @XmlElement(name = "VelocityCapability")
    protected VelocitySensorCapabilityType velocityCapability;
    @XmlElement(name = "AngularVelocityCapability")
    protected AngularVelocitySensorCapabilityType angularVelocityCapability;
    @XmlElement(name = "AccelerationCapability")
    protected AccelerationSensorCapabilityType accelerationCapability;
    @XmlElement(name = "AngularAccelerationCapability")
    protected AngularAccelerationSensorCapabilityType angularAccelerationCapability;

    /**
     * Gets the value of the positionCapability property.
     * 
     * @return
     *     possible object is
     *     {@link PositionSensorCapabilityType }
     *     
     */
    public PositionSensorCapabilityType getPositionCapability() {
        return positionCapability;
    }

    /**
     * Sets the value of the positionCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionSensorCapabilityType }
     *     
     */
    public void setPositionCapability(PositionSensorCapabilityType value) {
        this.positionCapability = value;
    }

    /**
     * Gets the value of the orientationCapability property.
     * 
     * @return
     *     possible object is
     *     {@link OrientationSensorCapabilityType }
     *     
     */
    public OrientationSensorCapabilityType getOrientationCapability() {
        return orientationCapability;
    }

    /**
     * Sets the value of the orientationCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrientationSensorCapabilityType }
     *     
     */
    public void setOrientationCapability(OrientationSensorCapabilityType value) {
        this.orientationCapability = value;
    }

    /**
     * Gets the value of the velocityCapability property.
     * 
     * @return
     *     possible object is
     *     {@link VelocitySensorCapabilityType }
     *     
     */
    public VelocitySensorCapabilityType getVelocityCapability() {
        return velocityCapability;
    }

    /**
     * Sets the value of the velocityCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link VelocitySensorCapabilityType }
     *     
     */
    public void setVelocityCapability(VelocitySensorCapabilityType value) {
        this.velocityCapability = value;
    }

    /**
     * Gets the value of the angularVelocityCapability property.
     * 
     * @return
     *     possible object is
     *     {@link AngularVelocitySensorCapabilityType }
     *     
     */
    public AngularVelocitySensorCapabilityType getAngularVelocityCapability() {
        return angularVelocityCapability;
    }

    /**
     * Sets the value of the angularVelocityCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngularVelocitySensorCapabilityType }
     *     
     */
    public void setAngularVelocityCapability(AngularVelocitySensorCapabilityType value) {
        this.angularVelocityCapability = value;
    }

    /**
     * Gets the value of the accelerationCapability property.
     * 
     * @return
     *     possible object is
     *     {@link AccelerationSensorCapabilityType }
     *     
     */
    public AccelerationSensorCapabilityType getAccelerationCapability() {
        return accelerationCapability;
    }

    /**
     * Sets the value of the accelerationCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccelerationSensorCapabilityType }
     *     
     */
    public void setAccelerationCapability(AccelerationSensorCapabilityType value) {
        this.accelerationCapability = value;
    }

    /**
     * Gets the value of the angularAccelerationCapability property.
     * 
     * @return
     *     possible object is
     *     {@link AngularAccelerationSensorCapabilityType }
     *     
     */
    public AngularAccelerationSensorCapabilityType getAngularAccelerationCapability() {
        return angularAccelerationCapability;
    }

    /**
     * Sets the value of the angularAccelerationCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngularAccelerationSensorCapabilityType }
     *     
     */
    public void setAngularAccelerationCapability(AngularAccelerationSensorCapabilityType value) {
        this.angularAccelerationCapability = value;
    }

}
