//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:12:40 PM BRST 
//


package org.iso.mpeg.mpegv._2010.scdv;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mpeg.mpeg_v._2010._01_scdv_ns package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LightSensorCapabilityTypeColor_QNAME = new QName("urn:mpeg:mpeg-v:2010:01-SCDV-NS", "Color");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mpeg.mpeg_v._2010._01_scdv_ns
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LightSensorCapabilityType }
     * 
     */
    public LightSensorCapabilityType createLightSensorCapabilityType() {
        return new LightSensorCapabilityType();
    }

    /**
     * Create an instance of {@link OrientationRangeType }
     * 
     */
    public OrientationRangeType createOrientationRangeType() {
        return new OrientationRangeType();
    }

    /**
     * Create an instance of {@link BodyFeatureMask }
     * 
     */
    public BodyFeatureMask createBodyFeatureMask() {
        return new BodyFeatureMask();
    }

    /**
     * Create an instance of {@link OrientationSensorCapabilityType }
     * 
     */
    public OrientationSensorCapabilityType createOrientationSensorCapabilityType() {
        return new OrientationSensorCapabilityType();
    }

    /**
     * Create an instance of {@link HumiditySensorCapabilityType }
     * 
     */
    public HumiditySensorCapabilityType createHumiditySensorCapabilityType() {
        return new HumiditySensorCapabilityType();
    }

    /**
     * Create an instance of {@link AmbientNoiseSensorCapabilityType }
     * 
     */
    public AmbientNoiseSensorCapabilityType createAmbientNoiseSensorCapabilityType() {
        return new AmbientNoiseSensorCapabilityType();
    }

    /**
     * Create an instance of {@link DistanceSensorCapabilityType }
     * 
     */
    public DistanceSensorCapabilityType createDistanceSensorCapabilityType() {
        return new DistanceSensorCapabilityType();
    }

    /**
     * Create an instance of {@link AtmosphericPressureSensorCapabilityType }
     * 
     */
    public AtmosphericPressureSensorCapabilityType createAtmosphericPressureSensorCapabilityType() {
        return new AtmosphericPressureSensorCapabilityType();
    }

    /**
     * Create an instance of {@link AngularVelocitySensorCapabilityType }
     * 
     */
    public AngularVelocitySensorCapabilityType createAngularVelocitySensorCapabilityType() {
        return new AngularVelocitySensorCapabilityType();
    }

    /**
     * Create an instance of {@link TorqueSensorCapabilityType }
     * 
     */
    public TorqueSensorCapabilityType createTorqueSensorCapabilityType() {
        return new TorqueSensorCapabilityType();
    }

    /**
     * Create an instance of {@link VelocitySensorCapabilityType }
     * 
     */
    public VelocitySensorCapabilityType createVelocitySensorCapabilityType() {
        return new VelocitySensorCapabilityType();
    }

    /**
     * Create an instance of {@link FacialFeatureMask }
     * 
     */
    public FacialFeatureMask createFacialFeatureMask() {
        return new FacialFeatureMask();
    }

    /**
     * Create an instance of {@link RangeType }
     * 
     */
    public RangeType createRangeType() {
        return new RangeType();
    }

    /**
     * Create an instance of {@link TemperatureSensorCapabilityType }
     * 
     */
    public TemperatureSensorCapabilityType createTemperatureSensorCapabilityType() {
        return new TemperatureSensorCapabilityType();
    }

    /**
     * Create an instance of {@link PositionSensorCapabilityType }
     * 
     */
    public PositionSensorCapabilityType createPositionSensorCapabilityType() {
        return new PositionSensorCapabilityType();
    }

    /**
     * Create an instance of {@link IntelligentCameraCapabilityType }
     * 
     */
    public IntelligentCameraCapabilityType createIntelligentCameraCapabilityType() {
        return new IntelligentCameraCapabilityType();
    }

    /**
     * Create an instance of {@link PressureSensorCapabilityType }
     * 
     */
    public PressureSensorCapabilityType createPressureSensorCapabilityType() {
        return new PressureSensorCapabilityType();
    }

    /**
     * Create an instance of {@link AccelerationSensorCapabilityType }
     * 
     */
    public AccelerationSensorCapabilityType createAccelerationSensorCapabilityType() {
        return new AccelerationSensorCapabilityType();
    }

    /**
     * Create an instance of {@link AngularAccelerationSensorCapabilityType }
     * 
     */
    public AngularAccelerationSensorCapabilityType createAngularAccelerationSensorCapabilityType() {
        return new AngularAccelerationSensorCapabilityType();
    }

    /**
     * Create an instance of {@link ForceSensorCapabilityType }
     * 
     */
    public ForceSensorCapabilityType createForceSensorCapabilityType() {
        return new ForceSensorCapabilityType();
    }

    /**
     * Create an instance of {@link MotionSensorCapabilityType }
     * 
     */
    public MotionSensorCapabilityType createMotionSensorCapabilityType() {
        return new MotionSensorCapabilityType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:mpeg:mpeg-v:2010:01-SCDV-NS", name = "Color", scope = LightSensorCapabilityType.class)
    public JAXBElement<List<String>> createLightSensorCapabilityTypeColor(List<String> value) {
        return new JAXBElement<List<String>>(_LightSensorCapabilityTypeColor_QNAME, ((Class) List.class), LightSensorCapabilityType.class, ((List<String> ) value));
    }

}
