//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:38:19 PM BRST 
//


package org.iso.mpeg.mpeg21._2003.dia;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import org.iso.mpeg.mpeg7._2001.ControlledTermUseType;


/**
 * <p>Java class for CodecCapabilityBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodecCapabilityBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg21:2003:01-DIA-NS}DIABaseType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Format" type="{urn:mpeg:mpeg7:schema:2001}ControlledTermUseType"/>
 *         &lt;element name="CodecParameter" type="{urn:mpeg:mpeg21:2003:01-DIA-NS}CodecParameterBaseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodecCapabilityBaseType", propOrder = {
    "formatAndCodecParameter"
})
@XmlSeeAlso({
    ImageCapabilitiesType.class,
    VideoCapabilitiesType.class,
    TransportCapabilitiesType.class,
    GraphicsCapabilitiesType.class,
    AudioCapabilitiesType.class,
    SceneGraphCapabilitiesType.class
})
public abstract class CodecCapabilityBaseType
    extends DIABaseType
{

    @XmlElements({
        @XmlElement(name = "Format", type = ControlledTermUseType.class),
        @XmlElement(name = "CodecParameter", type = CodecParameterBaseType.class)
    })
    protected List<Object> formatAndCodecParameter;

    /**
     * Gets the value of the formatAndCodecParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formatAndCodecParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormatAndCodecParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlledTermUseType }
     * {@link CodecParameterBaseType }
     * 
     * 
     */
    public List<Object> getFormatAndCodecParameter() {
        if (formatAndCodecParameter == null) {
            formatAndCodecParameter = new ArrayList<Object>();
        }
        return this.formatAndCodecParameter;
    }

}
