//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 06:38:19 PM BRST 
//


package org.iso.mpeg.mpeg21._2003.dia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for VisualImpairmentDegreeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisualImpairmentDegreeType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg21:2003:01-DIA-NS}DIABaseType">
 *       &lt;choice>
 *         &lt;element name="NumericDegree" type="{urn:mpeg:mpeg7:schema:2001}zeroToOneType"/>
 *         &lt;element name="TextualDegree">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;enumeration value="Severe"/>
 *               &lt;enumeration value="Medium"/>
 *               &lt;enumeration value="Mild"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisualImpairmentDegreeType", propOrder = {
    "numericDegree",
    "textualDegree"
})
public class VisualImpairmentDegreeType
    extends DIABaseType
{

    @XmlElement(name = "NumericDegree")
    protected Float numericDegree;
    @XmlElement(name = "TextualDegree")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String textualDegree;

    /**
     * Gets the value of the numericDegree property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNumericDegree() {
        return numericDegree;
    }

    /**
     * Sets the value of the numericDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNumericDegree(Float value) {
        this.numericDegree = value;
    }

    /**
     * Gets the value of the textualDegree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextualDegree() {
        return textualDegree;
    }

    /**
     * Sets the value of the textualDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextualDegree(String value) {
        this.textualDegree = value;
    }

}
